task_board/urls.py
from django.urls import path
from task_board.views import (
    index,
    toggle_task_status,
    toggle_task_assignee,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/toggle-status/",
        toggle_task_status,
        name="toggle-task-status"
    ),
    path(
        "tasks/<int:pk>/toggle-task-assignee/",
        toggle_task_assignee,
        name="toggle-task-assignee"
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("task_types", TaskTypeListView.as_view(), name="task-type-list"),
    path(
        "task_types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),
    path(
        "task_types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update"
    ),
    path(
        "task_types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete"
    ),
    path("positions", PositionListView.as_view(), name="position-list"),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update"
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    )
]

app_name = "task_board"

task_board/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


# Position Model
class Position(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# Worker Model
class Worker(AbstractUser):
    position = models.ForeignKey(
        Position,
        on_delete=models.CASCADE, related_name="workers",
        null=True, blank=True,
        default=None,
    )

    def __str__(self):
        return f"{self.first_name} {self.last_name}, ({self.position})"

    def get_absolute_url(self):
        return reverse("task_board:worker-detail", kwargs={"pk": self.id})


# TaskType Model
class TaskType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# Task Model
class Task(models.Model):
    task_type = models.ForeignKey(
        TaskType, on_delete=models.CASCADE, related_name="tasks"
    )
    assignees = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="tasks"
    )
    name = models.CharField(max_length=100)
    description = models.TextField()
    deadline = models.DateField(null=True, blank=True)
    is_complete = models.BooleanField(default=False)

    PRIORITY_CHOICES = [
        (3, "High Priority"),
        (2, "Medium Priority"),
        (1, "Low Priority"),
    ]

    priority = models.IntegerField(choices=PRIORITY_CHOICES, default=2)

    def __str__(self):
        return f"{self.name} ({self.get_priority_display()})"

    def get_absolute_url(self):
        return reverse("task_board:task-detail", kwargs={"pk": self.id})

task_board/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.utils import timezone

from task_board.models import Task, Worker


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            "name",
            "description",
            "task_type",
            "assignees",
            "deadline",
            "priority"
        ]
        labels = {
            "name": "Task Title",
            "description": "Description",
            "task_type": "Task Type",
            "assignees": "Assignees",
            "deadline": "Deadline",
            "priority": "Priority"
        }
        widgets = {
            "description": forms.Textarea(
                attrs={"rows": 4, "placeholder": "Task details..."}
            ),
            "assignees": forms.CheckboxSelectMultiple(),
            "deadline": forms.DateInput(
                attrs={"type": "date", "class": "form-control"}
            ),
            "priority": forms.RadioSelect(
                attrs={
                    "class": "form-check-input h2",
                    "style": "transform: scale(1.5);"
                }
            ),
        }

    def clean_deadline(self):
        deadline = self.cleaned_data["deadline"]
        if deadline and deadline < timezone.now().date():
            raise ValidationError("Deadline cannot be in the past.")
        return deadline


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Name",
                "class": "mr-2",
            }
        ),
    )


class WorkerCreationForm(UserCreationForm):
    class Meta:
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "email",
            "position",
        )

        widgets = {
            "position": forms.Select(
                attrs={
                    "class": "form-control",
                    "style": "height: auto; min-height: 40px; font-size: 1rem;"
                }
            )
        }


class WorkerSearchForm(forms.Form):
    first_name = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "First name",
                "class": "mr-2",
            }
        ),
    )
    last_name = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Last name",
                "class": "mr-2",
            }
        ),
    )


class NameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Name",
                "class": "mr-2",
            }
        ),
    )

task_board/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpRequest, HttpResponse
from django.urls import reverse_lazy, reverse
from django.utils.http import url_has_allowed_host_and_scheme
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)

from task_board.forms import (
    TaskForm,
    WorkerCreationForm,
    WorkerSearchForm,
    TaskSearchForm,
    NameSearchForm
)
from task_board.models import Task, Worker, TaskType, Position


@login_required
def index(request: HttpRequest) -> HttpResponse:
    tasks = Task.objects.select_related("task_type")

    name = request.GET.get("name", "")
    if name:
        tasks = tasks.filter(name__icontains=name)

    sort = request.GET.get("sort", "")
    valid_sorts = [
        "name",
        "-name",
        "task_type",
        "-task_type",
        "deadline",
        "-deadline",
        "priority",
        "-priority",
        "is_complete",
        "-is_complete"
    ]
    if sort in valid_sorts:
        tasks = tasks.order_by(sort)

    current_year = datetime.now().year

    paginator = Paginator(tasks, 6)
    page = request.GET.get("page")
    page_obj = paginator.get_page(page)

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "tasks": tasks,
        "current_year": current_year,
        "page_obj": page_obj,
        "is_paginated": page_obj.has_other_pages(),
        "paginator": paginator,
        "num_visits": num_visits + 1,
        "search_form": TaskSearchForm(initial={"name": name}),
    }
    return render(request, "task_board/index.html", context=context)


@login_required
def toggle_task_status(request, pk):
    task = get_object_or_404(Task, pk=pk)

    if request.user not in task.assignees.all():
        messages.warning(
            request,
            "You do not have access to change the status of this task."
        )
        return redirect("task_board:index")

    task.is_complete = not task.is_complete
    task.save()

    next_url = request.GET.get("next")
    if next_url and url_has_allowed_host_and_scheme(
            next_url,
            allowed_hosts={request.get_host()}
    ):
        return redirect(next_url)
    return redirect("task_board:index")


@login_required
def toggle_task_assignee(request, pk):
    task = get_object_or_404(Task, pk=pk)
    user = request.user

    if user not in task.assignees.all():
        task.assignees.add(user)
    else:
        task.assignees.remove(user)
    return redirect("task_board:task-detail", pk=pk)


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    queryset = (
        Task.objects
        .select_related("task_type")
        .prefetch_related("assignees__position")
    )


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task_board:index")
    template_name = "task_board/task_form.html"


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "task_board/task_form.html"

    def get_success_url(self):
        return reverse("task_board:task-detail", kwargs={"pk": self.object.id})


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = "task_board/task_confirm_delete.html"
    success_url = reverse_lazy("task_board:index")


class WorkerListView(LoginRequiredMixin, ListView):
    model = Worker
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WorkerListView, self).get_context_data(**kwargs)

        search_fields = ["first_name", "last_name"]
        initial_data = {
            field: self.request.GET.get(field, "")
            for field in search_fields
        }

        context["search_form"] = WorkerSearchForm(initial=initial_data)
        return context

    def get_queryset(self):
        queryset = Worker.objects.select_related("position")
        filters = {}

        first_name = self.request.GET.get("first_name")
        last_name = self.request.GET.get("last_name")

        if first_name:
            filters["first_name__icontains"] = first_name
        if last_name:
            filters["last_name__icontains"] = last_name
        return queryset.filter(**filters)


class WorkerDetailView(LoginRequiredMixin, DetailView):
    model = Worker
    queryset = (
        Worker.objects
        .select_related("position")
        .prefetch_related("tasks__task_type")
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tasks = self.object.tasks.all()
        paginator = Paginator(tasks, 6)

        page = self.request.GET.get("page")
        page_obj = paginator.get_page(page)
        context["page_obj"] = page_obj
        context["paginator"] = paginator
        context["is_paginated"] = page_obj.has_other_pages()

        return context


class WorkerCreateView(CreateView):
    model = Worker
    form_class = WorkerCreationForm
    success_url = reverse_lazy("task_board:worker-list")


class TaskTypeListView(LoginRequiredMixin, ListView):
    model = TaskType
    template_name = "task_board/task_type_list.html"
    context_object_name = "task_type_list"
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskTypeListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")
        context["search_form"] = NameSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = super(TaskTypeListView, self).get_queryset()

        name = self.request.GET.get("name", "")
        if name:
            queryset = queryset.filter(name__icontains=name)
        return queryset


class TaskTypeCreateView(LoginRequiredMixin, CreateView):
    model = TaskType
    fields = "__all__"
    template_name = "task_board/task_type_form.html"
    success_url = reverse_lazy("task_board:task-type-list")


class TaskTypeUpdateView(LoginRequiredMixin, UpdateView):
    model = TaskType
    fields = "__all__"
    template_name = "task_board/task_type_form.html"
    success_url = reverse_lazy("task_board:task-type-list")


class TaskTypeDeleteView(LoginRequiredMixin, DeleteView):
    model = TaskType
    template_name = "task_board/task_type_confirm_delete.html"
    success_url = reverse_lazy("task_board:task-type-list")


class PositionListView(LoginRequiredMixin, ListView):
    model = Position
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PositionListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")
        context["search_form"] = NameSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = super(PositionListView, self).get_queryset()

        name = self.request.GET.get("name", "")
        if name:
            queryset = queryset.filter(name__icontains=name)
        return queryset


class PositionCreateView(LoginRequiredMixin, CreateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task_board:position-list")


class PositionUpdateView(LoginRequiredMixin, UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task_board:position-list")


class PositionDeleteView(LoginRequiredMixin, DeleteView):
    model = Position
    template_name = "task_board/position_confirm_delete.html"
    success_url = reverse_lazy("task_board:position-list")

templates/task_board/index.html
{% extends 'base.html' %}

{% block title %}Task Manager{% endblock %}

{% block content %}
<!-- Table name -->
<div class="d-flex position-relative justify-content-center align-items-center">
  <h2 class="text-center w-100">Task List</h2>
  <a href="{% url 'task_board:task-create' %}" class="btn-circle position-absolute" style="right: 0;" data-toggle="tooltip" title="Create New Task">
    <i class="fas fa-plus"></i>
  </a>
</div>

{% include "includes/search_form.html" %}

{% include "includes/task_table.html" %}

{% endblock %}

templates/task_board/position_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Position Delete{% endblock %}

{% block content %}
  <!-- Table name -->
  <div class="d-flex position-relative justify-content-center align-items-center mb-3">
    <a href="{% url 'task_board:position-list' %}" class="btn-circle position-absolute" style="left: 0;" data-toggle="tooltip" title="Back to position list">
      <i class="fas fa-arrow-left"></i>
    </a>
    <h2 class="text-center w-100">Position Delete</h2>
  </div>
  <div class="card border-left-warning shadow h-100 py-2 bg-dark text-white text-center">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
            <h5 class="text-danger">⚠️ Warning: Deleting ({{ position.name }}) position will also delete all related workers.</h5>
          </div>
          {% include "includes/delete_form.html" %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/task_board/position_list.html
{% extends 'base.html' %}

{% block title %}Task Manager Position{% endblock %}

{% block content %}
<!-- Table name -->
<div class="d-flex position-relative justify-content-center align-items-center">
  <h2 class="text-center w-100">Position List</h2>
  <a href="{% url 'task_board:position-create' %}" class="btn-circle position-absolute" style="right: 0;" data-toggle="tooltip" title="Create New Position">
    <i class="fas fa-plus"></i>
  </a>
</div>

{% include "includes/search_form.html" %}

<table class="table text-white mb-0 table-custom">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col" class="text-right">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for position in position_list %}
      <tr class="font-weight-normal">

        <!-- Task name -->
        <td class="align-middle">
          {{ position.name }}
        </td>

        <!-- Task Actions -->
        <td class="align-middle text-right">
          <a href="{% url 'task_board:position-update' pk=position.id %}" class="px-2" data-toggle="tooltip" title="Edit">
            <i class="fas fa-pen text-warning"></i>
          </a>
          <a href="{% url 'task_board:position-delete' pk=position.id %}" class="px-2" data-toggle="tooltip" title="Remove">
            <i class="fas fa-trash-alt fa-lg text-danger"></i>
          </a>
        </td>
      </tr>
    {% empty %}
      <tr>
        <td colspan="6" class="text-center text-muted display-4">No positions available yet.</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/task_board/task_detail.html
{% extends 'base.html' %}

{% block title %}{{task.name}}{% endblock %}

{% block content %}
<!-- Table name -->
<div class="d-flex position-relative justify-content-center align-items-center">
  <a href="{% url 'task_board:index' %}" class="btn-circle position-absolute" style="left: 0;" data-toggle="tooltip" title="Back to task list">
    <i class="fas fa-arrow-left"></i>
  </a>
  <h2 class="text-center w-100">Task Detail Info</h2>
  <div class="position-absolute" style="right: 0;">
    <a href="{% url 'task_board:task-update' pk=task.id %}" class="px-2 fa-lg" data-toggle="tooltip" title="Edit">
      <i class="fas fa-pen text-warning"></i>
    </a>
    <a href="{% url 'task_board:task-delete' pk=task.id %}" class="px-2 fa-lg" data-toggle="tooltip" title="Remove">
      <i class="fas fa-trash-alt fa-lg text-danger"></i>
    </a>
  </div>
</div>

<div class="row mt-4">
  <div class="col-lg-6 d-flex align-items-stretch">
    <div class="card mb-4 bg-dark text-white w-100">
      <div class="card-header h3 text-center">
        {{ task.name }}
      </div>
      <div class="card-body h4">
        {{ task.description }}
      </div>
    </div>
  </div>

  <div class="col-lg-6">
    <div class="row">

      <!-- Task Type -->
      <div class="col-md-6 col-xl-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2 bg-dark text-white">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                  Task Type
                </div>
                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ task.task_type }}</div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Status -->
      <div class="col-md-6 col-xl-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2 bg-dark text-white">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                  Status
                </div>
                {% if task.is_complete %}
                  <div class="h5 mb-0 font-weight-bold text-gray-800 text-success">Complete!</div>
                {% else %}
                  <div class="h5 mb-0 font-weight-bold text-gray-800 text-warning">Pending...</div>
                {% endif %}
              </div>
              {% if user in task.assignees.all %}
                {% if task.is_complete %}
                  <a href="{% url 'task_board:toggle-task-status' pk=task.id %}?next={{ request.path }}" data-toggle="tooltip" title="Mark as pending">
                    <i class="fas fa-times-circle fa-3x text-danger"></i>
                  </a>
                {% else %}
                  <a href="{% url 'task_board:toggle-task-status' pk=task.id %}?next={{ request.path }}" data-toggle="tooltip" title="Mark as completed">
                    <i class="fas fa-check-circle fa-3x text-success"></i>
                  </a>
                {% endif %}
              {% endif %}
            </div>
          </div>
        </div>
      </div>

      <!-- Priority -->
      <div class="col-md-6 col-xl-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2 bg-dark text-white">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                  Priority
                </div>
                <div class="row no-gutters align-items-center">
                  <div class="col-auto">
                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{ task.get_priority_display }}</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- DeadLine -->
      <div class="col-md-6 col-xl-6 mb-4 ">
        <div class="card border-left-primary shadow h-100 py-2 bg-dark text-white">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                  DeadLine
                </div>
                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ task.deadline }}</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<hr class="mt-0">

<div class="d-flex position-relative justify-content-center align-items-center">
  <h2 class="text-center w-100">Task assignees:</h2>
  {% if user in task.assignees.all %}
    <a href="{% url 'task_board:toggle-task-assignee' pk=task.id %}" class="btn btn-danger position-absolute" style="right: 0;" title="Remove me from this task">
      Remove me from this task
    </a>
  {% else %}
    <a href="{% url 'task_board:toggle-task-assignee' pk=task.id %}" class="btn btn-primary position-absolute" style="right: 0;" title="Add me to this task">
      Add me to this task
    </a>
  {% endif %}
</div>

<table class="table text-white mb-0 table-custom">
  <thead>
    <tr>
      <th scope="col" class="text-center">Worker</th>
      <th scope="col" class="text-center">Username</th>
      <th scope="col" class="text-center">Email</th>
      <th scope="col" class="text-center">Position</th>
    </tr>
  </thead>
  <tbody>
    {% for worker in task.assignees.all %}
      <tr class="font-weight-normal">

        <!-- Worker name -->
        <th class="align- text-center">
          <a class="ms-2" href="{{ worker.get_absolute_url }}" title="Worker">{{ worker.first_name }} {{ worker.last_name }}</a>
          {% if worker == user %}
            <span class="text-muted">(you)</span>
          {% endif %}
        </th>

        <!-- Worker username -->
        <td class="align-middle text-center">{{ worker.username }}</td>

        <!-- Worker Email -->
        <td class="align-middle text-center">{{ worker.email }}</td>

        <!-- Worker Position -->
        <td class="align-middle text-center">{{ worker.position }}</td>

      </tr>
    {% empty %}
      <tr>
        <td colspan="6" class="text-center text-muted display-4">The task doesn't have workers yet.</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/task_board/task_type_list.html
{% extends 'base.html' %}

{% block title %}Task Manager Task Type{% endblock %}

{% block content %}
<!-- Table name -->
<div class="d-flex position-relative justify-content-center align-items-center">
  <h2 class="text-center w-100">Task Type List</h2>
  <a href="{% url 'task_board:task-type-create' %}" class="btn-circle position-absolute" style="right: 0;" data-toggle="tooltip" title="Create New Task Type">
    <i class="fas fa-plus"></i>
  </a>
</div>

{% include "includes/search_form.html" %}

<table class="table text-white mb-0 table-custom">
  <thead>
    <tr>
      <th scope="col">Task</th>
      <th scope="col" class="text-right">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for task_type in task_type_list %}
      <tr class="font-weight-normal">

        <!-- Task name -->
        <td class="align-middle">
          {{ task_type.name }}
        </td>

        <!-- Task Actions -->
        <td class="align-middle text-right">
          <a href="{% url 'task_board:task-type-update' pk=task_type.id %}" class="px-2" data-toggle="tooltip" title="Edit">
            <i class="fas fa-pen text-warning"></i>
          </a>
          <a href="{% url 'task_board:task-type-delete' pk=task_type.id %}" class="px-2" data-toggle="tooltip" title="Remove">
            <i class="fas fa-trash-alt fa-lg text-danger"></i>
          </a>
        </td>
      </tr>
    {% empty %}
      <tr>
        <td colspan="6" class="text-center text-muted display-4">No task types available yet.</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/task_board/worker_list.html
{% extends 'base.html' %}

{% block title %}Task Manager Workers{% endblock %}

{% block head %}
  {% load static %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/boxicons/2.1.0/css/boxicons.min.css" integrity="sha512-pVCM5+SN2+qwj36KonHToF2p1oIvoU3bsqxphdOIWMYmgr4ZqD3t5DjKvvetKhXGc/ZG5REYTT6ltKfExEei/Q==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.3.45/css/materialdesignicons.css" integrity="sha256-NAxhqDvtY0l4xn+YVa6WjAcmd94NNfttjNsDmNatFVc=" crossorigin="anonymous" />
  <link rel="stylesheet" href="{% static 'css/styles_worker_list.css' %}">
{% endblock %}

{% block content %}
<!-- Table name -->
  <div class="d-flex position-relative justify-content-center align-items-center">
    <h2 class="text-center w-100">Worker List</h2>
    <a href="{% url 'task_board:worker-create' %}" class="btn-circle position-absolute" style="right: 0;" data-toggle="tooltip" title="Add New Worker">
      <i class="fas fa-plus"></i>
    </a>
  </div>

  {% include "includes/search_form.html" %}

  <div class="container">
    <div class="row">
      {% for worker in worker_list %}
        <div class="col-xl-4 col-sm-6">
          <div class="card-profile bg-dark text-white">
            <div class="card-body">
              <div class="d-flex align-items-center">
                <div><img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="Profile Picture" class="avatar-md rounded-circle img-thumbnail" /></div>
                <div class="flex-1 ms-3">
                  <h5 class="font-size-16 mb-1">
                    <a href="{{ worker.get_absolute_url }}">
                      {{ worker.first_name }} {{ worker.last_name }}
                      {% if worker == user %}
                        <span class="text-muted">(you)</span>
                      {% endif %}
                    </a>
                  </h5>
                  <span class="badge badge-soft-success mb-0">{{ worker.position }}</span>
                </div>
              </div>
              <div class="mt-3 pt-1">
                <p class="mb-0"><i class="mdi mdi-phone font-size-15 align-middle pe-2 text-primary"></i> 123 456 789</p>
                <p class="mb-0 mt-2"><i class="mdi mdi-email font-size-15 align-middle pe-2 text-primary"></i> {{ worker.email }}</p>
                <p class="mb-0 mt-2"><i class="mdi mdi-google-maps font-size-15 align-middle pe-2 text-primary"></i> France (Paris)</p>
              </div>
              <div class="d-flex gap-2 pt-4">
                <a href="{{ worker.get_absolute_url }}" class="btn btn-primary btn-sm w-50">
                  <i class="bx bx-user me-1"></i> Profile
                </a>
              </div>
            </div>
          </div>
        </div>
      {% empty %}
        <div class="text-center">
          <h3 class="text-muted display-4">No workers available yet.</h3>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}