task_board/urls.py
from django.urls import path
from task_board.views import (
    index,
    toggle_task_status,
    toggle_task_assignee,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/toggle-status/",
        toggle_task_status,
        name="toggle-task-status"
    ),
    path(
        "tasks/<int:pk>/toggle-task-assignee/",
        toggle_task_assignee,
        name="toggle-task-assignee"
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("task_types", TaskTypeListView.as_view(), name="task-type-list"),
    path(
        "task_types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),
    path(
        "task_types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update"
    ),
    path(
        "task_types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete"
    ),
    path("positions", PositionListView.as_view(), name="position-list"),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update"
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    )
]

app_name = "task_board"

templates/includes/crispy_form.html
{% load crispy_forms_filters %}

<form method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

templates/includes/crispy_task_form.html
{% load crispy_forms_filters %}

<form method="post" novalidate>
  {% csrf_token %}
  {{ form.name|as_crispy_field }}
  {{ form.description|as_crispy_field }}
  {{ form.task_type|as_crispy_field }}

  {{ form.assignees.label_tag }}
  <div class="assignees-scroll">
    {{ form.assignees }}
  </div>

  {{ form.deadline|as_crispy_field }}
  {{ form.priority|as_crispy_field }}

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

templates/includes/delete_form.html
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger">Confirm Delete</button>
</form>

templates/includes/footer.html
{% block footer %}
<footer class="bg-dark text-center text-white">
  <p class="mb-0">Task Manager &copy; {{ current_year }} | Created by Ihor Dmytriv</p>
</footer>
{% endblock %}

templates/includes/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

templates/includes/navbar.html
{% block navbar %}
  {% load static %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <img class="navbar-img" src="{% static "images/task_manager_icon.png" %}"
                alt="Check" width="40">
      <a class="navbar-brand" href="{% url 'task_board:index' %}">Task Manager</a>
      {% if num_visits %}
        <p class="text-center mb-0 mx-auto small text-white">
          👁️ You have visited this page: <strong>{{ num_visits }}</strong> time{{ num_visits|pluralize }}
        </p>
      {% endif %}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">

          <li class="nav-item">
            <a class="nav-link" href="{% url 'task_board:index' %}">Task List</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'task_board:task-type-list' %}">Task Type List</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'task_board:worker-list' %}">Worker List</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'task_board:position-list' %}">Position List</a>
          </li>

          <li class="nav-item d-flex align-items-center mx-3">
            <span class="divider"></span>
          </li>

          {% if user.is_authenticated %}
            <li class="nav-item d-flex align-items-center">
              <span class="user-badge">
                👤 <a href={% url 'task_board:worker-detail' pk=user.id %}>{{ user.first_name }} {{ user.last_name }}</a>
              </span>
              <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn text-danger">Logout</button>
              </form>
            </li>

          {% else %}
            <li class="nav-item">
              <a class="nav-link text-primary" href="{% url 'login' %}">Login</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
{% endblock %}

templates/includes/pagination.html
{% load query_transform %}
<ul class="pagination d-flex position-relative justify-content-center align-items-center mb-3">
  {% if page_obj.number > 3 %}
    <li class="page-item">
      <a href="?{% query_transform request page=1 %}" class="page-link bg-dark text-white">First</a>
    </li>
  {% endif %}
  {% if page_obj.number > 2 %}
    <li class="page-item">
      <a href="?{% query_transform request page=page_obj.number|add:"-2" %}" class="page-link bg-dark text-white">{{ page_obj.number|add:"-2" }}</a>
    </li>
  {% endif %}
  {% if page_obj.has_previous %}
    <li class="page-item">
      <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link bg-dark text-white">{{ page_obj.previous_page_number }}</a>
    </li>
  {% endif %}

  <li class="page-item active">
    <span class="page-link bg-dark text-white">{{ page_obj.number }}/{{ paginator.num_pages }}</span>
  </li>

  {% if page_obj.has_next %}
    <li class="page-item">
      <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link bg-dark text-white">{{ page_obj.next_page_number }}</a>
    </li>
  {% endif %}
  {% if page_obj.number|add:"2" <= paginator.num_pages %}
    <li class="page-item">
      <a href="?{% query_transform request page=page_obj.number|add:'2' %}" class="page-link bg-dark text-white">{{ page_obj.number|add:'2' }}</a>
    </li>
  {% endif %}
  {% if page_obj.number|add:"3" <= paginator.num_pages %}
    <li class="page-item">
      <a href="?{% query_transform request page=paginator.num_pages %}" class="page-link bg-dark text-white">Last</a>
    </li>
  {% endif %}
</ul>

templates/includes/search_form.html
{% load crispy_forms_filters %}

<form class="d-flex justify-content-center form-inline" method="GET" action="">
    {{ search_form|crispy }}
    <input type="submit" value="🔍︎" class="btn btn-primary">
  </form>

templates/includes/task_table.html
{% load custom_filters %}
{% load sort_helpers %}
{% load query_transform %}

<table class="table text-white mb-0 table-custom">
  <thead>
    <tr>
      <th scope="col">
        {% toggle_sort request "name" as new_sort %}
        <a href="?{% query_transform request sort=new_sort %}" class="sort-link">Task</a>
        {% if request.GET.sort == "name" %}↑{% elif request.GET.sort == "-name" %}↓{% endif %}
      </th>
      <th scope="col">
        {% toggle_sort request "task_type" as new_sort %}
        <a href="?{% query_transform request sort=new_sort %}" class="sort-link">Type</a>
        {% if request.GET.sort == "task_type" %}↑{% elif request.GET.sort == "-task_type" %}↓{% endif %}
      </th>
      <th scope="col">
        {% toggle_sort request "deadline" as new_sort %}
        <a href="?{% query_transform request sort=new_sort %}" class="sort-link">Deadline</a>
        {% if request.GET.sort == "deadline" %}↑{% elif request.GET.sort == "-deadline" %}↓{% endif %}
      </th>
      <th scope="col" class="text-center">
        {% toggle_sort request "priority" as new_sort %}
        <a href="?{% query_transform request sort=new_sort %}" class="sort-link">Priority</a>
        {% if request.GET.sort == "priority" %}↑{% elif request.GET.sort == "-priority" %}↓{% endif %}
      </th>
      <th scope="col" class="text-center">
        {% toggle_sort request "is_complete" as new_sort %}
        <a href="?{% query_transform request sort=new_sort %}" class="sort-link">Status</a>
        {% if request.GET.sort == "is_complete" %}↑{% elif request.GET.sort == "-is_complete" %}↓{% endif %}
      </th>
      <th scope="col" class="text-center">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for task in page_obj %}
      <tr class="font-weight-normal">

        <!-- Task name -->
        <td class="align-middle">
          <a href="{{ task.get_absolute_url }}" title="Task">{{ task.name }}</a>
        </td>

        <!-- Task Type -->
        <td class="align-middle">{{ task.task_type }}</td>

        <!-- Task Deadline -->
        <td class="align-middle">
          {% if task.deadline %}
            {{ task.deadline }}
            <br>
            {% if not task.is_complete %}
              <span class="text-muted">({{ task.deadline|time_until }})</span>
            {% endif %}
          {% else %}
            No deadline
          {% endif %}
        </td>

        <!-- Task Priority -->
        <td class="align-middle text-center">
          <span class="mb-0">
            {% if task.priority == 1 %}
              <i class="fas fa-circle text-success priority-icon"></i>
            {% elif task.priority == 2 %}
              <i class="fas fa-circle text-warning priority-icon"></i>
            {% elif task.priority == 3 %}
              <i class="fas fa-circle text-danger priority-icon"></i>
            {% endif %}
          </span>
        </td>

        <!-- Task Status -->
        <td class="align-middle text-center">
          {% if task.is_complete %}
            <span class="text-success font-weight-bold">Completed!</span>
          {% else %}
            <span class="text-warning font-weight-bold">Pending...</span>
          {% endif %}
        </td>

        <!-- Task Actions -->
        <td class="align-middle text-right">
          {% if user in task.assignees.all %}
            {% if task.is_complete %}
              <a href="{% url 'task_board:toggle-task-status' pk=task.id %}" class="px-2" data-toggle="tooltip" title="Mark as pending">
                <i class="fas fa-times-circle fa-lg text-danger"></i>
              </a>
            {% else %}
              <a href="{% url 'task_board:toggle-task-status' pk=task.id %}" class="px-2" data-toggle="tooltip" title="Mark as completed">
                <i class="fas fa-check-circle fa-lg text-success"></i>
              </a>
            {% endif %}
          {% endif %}
          <a href="{% url 'task_board:task-update' pk=task.id %}" class="px-2" data-toggle="tooltip" title="Edit">
            <i class="fas fa-pen text-warning"></i>
          </a>
          <a href="{% url 'task_board:task-delete' pk=task.id %}" class="px-2" data-toggle="tooltip" title="Remove">
            <i class="fas fa-trash-alt fa-lg text-danger"></i>
          </a>
        </td>
      </tr>
    {% empty %}
      <tr>
        <td colspan="6" class="text-center text-muted display-4">No tasks available yet.</td>
      </tr>
    {% endfor %}
  </tbody>
</table>